input_side_packet: "yamnet_model_path"
input_side_packet: "input_audio_wav_path"
output_stream: "audio_class"

node {
  calculator: "TfliteTaskAudioClassifierCalculator"
  input_side_packet: "MODEL_PATH: yamnet_model_path"
  input_side_packet: "DATA_PATH: input_audio_wav_path"
  output_stream: "CLASS: audio_class"
}
